[package]
name = "zup-rt-macros"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.27"
quote = "0.6.12"

[dependencies.syn]
features = ["extra-traits", "full"]
version = "0.15.32"
