[workspace]
members = [
  "cortex-r",
  "zup",
  "zup-quickstart",
  "zup-rt",
  "zup-rt/macros",
  "zup-rtfm",
  "zup-rtfm/macros",
]

[profile.dev]
incremental = false

[profile.release]
codegen-units = 1
debug = true
lto = true
